### ISSUE TITLE
npm run dev 报错

### ISSUE THREAD

**Issue by womingweijia** [iview/iview-admin#1190]
xx@xx-All-Series:~/work/iview/TestProject/home$ **npm start**

> home@1.0.0 start /home/xx/work/iview/TestProject/home
> npm run dev

> home@1.0.0 dev /home/xx/work/iview/TestProject/home
> webpack-dev-server --inline --progress --config build/webpack.dev.conf.js

TypeError: Cannot destructure property `compile` of 'undefined' or 'null'.
    at addHooks (/home/cx/work/iview/TestProject/home/node_modules/webpack-dev-server/lib/Server.js:131:49)
    at new Server (/home/cx/work/iview/TestProject/home/node_modules/webpack-dev-server/lib/Server.js:144:5)
    at startDevServer (/home/cx/work/iview/TestProject/home/node_modules/webpack-dev-server/bin/webpack-dev-server.js:355:14)
    at processOptions (/home/cx/work/iview/TestProject/home/node_modules/webpack-dev-server/bin/webpack-dev-server.js:309:5)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)

**vue**: v3.3.0
**nodejs**: v10.8.0
**iview**: 3.2.2

**webpack**: 4.29.0  
**webpack-dev-server**:  3.1.14 
**vue-loader**: 15.6.2

说明：未引入iview时，运行正常。引入iview后报错。

**Comment by hankaibo** [comment]
不懂，如果我出现这种问题都是删除所有依赖重新安装。
推荐使用yarn安装。
