### ISSUE TITLE
[Bug Report]npm install出现异常

### ISSUE THREAD

**Issue by suhanyujie** [iview/iview-admin#1222]
### Environment
Ubuntu18.04.1  64位

### Reproduction link
[https://github.com/iview/iview-admin](https://github.com/iview/iview-admin)

### Steps to reproduce
```
git clone https://github.com/iview/iview-admin.git
npm install 
```

### What is expected?
执行完成，无致命错误

### What is actually happening?
报error错误，命令执行未完成，报错如下：
```
root@ubuntu:/home/tmp/iview-admin# npm install
npm WARN deprecated hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated cryptiles@2.0.5: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated boom@2.10.1: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.

> nodent-runtime@3.2.1 install /home/tmp/iview-admin/node_modules/nodent-runtime
> node build.js

fs.js:114
    throw err;
    ^

Error: EACCES: permission denied, open '/home/tmp/iview-admin/node_modules/nodent-runtime/dist/index.js'
    at Object.openSync (fs.js:438:3)
    at Object.writeFileSync (fs.js:1189:35)
    at Object.<anonymous> (/home/tmp/iview-admin/node_modules/nodent-runtime/build.js:5:4)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
npm WARN eslint-config-standard@12.0.0 requires a peer of eslint@>=5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-standard@12.0.0 requires a peer of eslint-plugin-node@>=7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-standard@12.0.0 requires a peer of eslint-plugin-promise@>=4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-standard@12.0.0 requires a peer of eslint-plugin-standard@>=4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN iview-admin@2.0.0 No repository field.
npm WARN iview-admin@2.0.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodent-runtime@3.2.1 install: `node build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodent-runtime@3.2.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-03-11T07_59_47_560Z-debug.log
```

---
已经是用root的权限了。

**Comment by suhanyujie** [comment]
* 解决了 ，还是权限问题。
* 因为是以root用户命令运行的`npm install`，但实际上还不行，需要加sudo
* 但是我从node官网下载最新的node软件，包含了npm。我的安装方式是，只是把node的路径`/xxx/xxx/bin`加入环境变量中，但在Ubuntu下，此时因为系统安全限制，非`/usr/bin`或`/usr/local/bin`下的可执行文件，是没法使用`sudo`作为命令前缀的。
* 解决办法，就是将`node`,`npm`的可执行文件放入`/usr/bin`或`/usr/local/bin`下。以这种方法安装的node和npm，是可以使用`sudo npm install`执行成功

**Comment by woshihaoren** [comment]
it can work , npm install  --unsafe-perm=true
