### ISSUE TITLE
项目跑不起来？？？

### ISSUE THREAD

**Issue by resuper** [iview/iview-admin#1356]
is:issue is:open 克隆到本地之后，进入项目主目录 iview-admin下面，
执行 npm i;
^^^^^^^10年后………………………………
然后执行npm run dev;
报错。

npm run dev

> iview-admin@2.0.0 dev F:\study-workspace\vue&iview\iview-admin
> vue-cli-service serve --open

'iview\iview-admin\node_modules\.bin\' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module 'F:\study-workspace\@vue\cli-service\bin\vue-cli-service.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iview-admin@2.0.0 dev: `vue-cli-service serve --open`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iview-admin@2.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2020-01-13T15_49_07_418Z-debug.log

**Comment by JBumblebee** [comment]
同等问题，请问是否解决了？

**Comment by rjielx** [comment]
vue.configs.js
![image](https://user-images.githubusercontent.com/46103765/83746131-39e50300-a691-11ea-89c6-36fea42a6981.png)

**Comment by rjielx** [comment]
vue.config.js
publicPath: BASE_URL,
// baseUrl: BASE_URL,

**Comment by JBumblebee** [comment]
请问你的人脸识别有进行活体检测吗？



今天也要加油噢


------------------ 原始邮件 ------------------
发件人: rjielx <notifications@github.com&gt;
发送时间: 2020年6月4日 18:30
收件人: iview/iview-admin <iview-admin@noreply.github.com&gt;
抄送: 大黄蜂 <532458665@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[iview/iview-admin] 项目跑不起来？？？ (#1356)





 
vue.config.js
 publicPath: BASE_URL,
 // baseUrl: BASE_URL,

**Comment by taowenqian** [comment]
> vue.config.js
> publicPath: BASE_URL,
> // baseUrl: BASE_URL,



> vue.config.js
> publicPath: BASE_URL,
> // baseUrl: BASE_URL,

按照这个方法，项目可以跑起来啦，感谢！
