### ISSUE TITLE
Less样式文件修改后没有动态加载

### ISSUE THREAD

**Issue by wushuang5112** [iview/iview-admin#261]
你好，我使用最新版本的iview-admin-v1.2.2时，当我修改/view/access/access.less中样式时，菜单中"权限管理"页样式没有变动,但当我刷新页面时它就立马样式变化了。样式修改点如下：
.access{
    background-color: blue;
}
我看下了npm run dev里，当我修改.less文件时它是动态编译的，而且浏览器也进行了热加载，但是热加载的内容{"h":"d476a90a90d01d938a29","c":{}}是为空的，这是个很奇怪的现象。
另外，如果我在access.vue文件中修改某个元素属性style="background-color: blue;"，它的背景就变成蓝色的了。
less hot reload是有问题，这个怎么解决？

**Comment by wushuang5112** [comment]
为什么没人回答？

**Comment by lison16** [comment]
稍后修复

**Comment by wushuang5112** [comment]
你好，没有看到你更新代码呀，方不方便告诉我怎么解决的？
昨天我看了一天webpack还是没搞明白，目前觉得有的地方是HtmlWebpackPlugin没有注入模板。

**Comment by wushuang5112** [comment]
新问题，我使用样式覆盖特性时会发现使用引用会出问题：
@import 'iview/src/styles/index.less';
@primary-color: #8c0776;
如上配置webpack会报错：
 + 4 hidden assets
 [108] (webpack)/hot nonrecursive ^\.\/log$ 170 bytes {34} [built]
 [111] ./src/main.js 1.85 kB {32} [built]
 [221] ./src/styles/iview-ui.less 2.44 kB {32} [built] [failed] [1 error]
    + 926 hidden modules

ERROR in ./src/styles/iview-ui.less
Module build failed: ModuleBuildError: Module build failed: Can't resolve './iview/src/styles/index.less' in 'F:\cmdb_frontend\src\styles'
 @ F:\cmdb_frontend\src\styles\iview-ui.less (line 1, column 0)
 near lines:
   
   @import 'iview/src/styles/index.less';
   //@import (inline) 'iview/dist/styles/iview.css';
    at runLoaders (F:\cmdb_frontend\node_modules\webpack\lib\NormalModule.js:195:19)
    at F:\cmdb_frontend\node_modules\loader-runner\lib\LoaderRunner.js:364:11
    at F:\cmdb_frontend\node_modules\loader-runner\lib\LoaderRunner.js:230:18
    at context.callback (F:\cmdb_frontend\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at F:\cmdb_frontend\node_modules\less-loader\index.js:68:16
    at F:\cmdb_frontend\node_modules\less\lib\less\render.js:26:35
    at F:\cmdb_frontend\node_modules\less\lib\less\parse.js:62:33
    at ImportVisitor.finish [as _finish] (F:\cmdb_frontend\node_modules\less\lib\less\parser\parser.js:180:28)
    at ImportVisitor._onSequencerEmpty (F:\cmdb_frontend\node_modules\less\lib\less\visitors\import-visitor.js:35:14)
    at ImportSequencer.tryRun (F:\cmdb_frontend\node_modules\less\lib\less\visitors\import-sequencer.js:50:14)
    at F:\cmdb_frontend\node_modules\less\lib\less\visitors\import-sequencer.js:19:25
    at fileParsedFunc (F:\cmdb_frontend\node_modules\less\lib\less\import-manager.js:50:17)
    at F:\cmdb_frontend\node_modules\less\lib\less\import-manager.js:121:17
    at F:\cmdb_frontend\node_modules\less-loader\index.js:111:5
    at onError (F:\cmdb_frontend\node_modules\enhanced-resolve\lib\Resolver.js:65:10)
    at loggingCallbackWrapper (F:\cmdb_frontend\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at runAfter (F:\cmdb_frontend\node_modules\enhanced-resolve\lib\Resolver.js:158:4)
    at innerCallback (F:\cmdb_frontend\node_modules\enhanced-resolve\lib\Resolver.js:146:3)
    at loggingCallbackWrapper (F:\cmdb_frontend\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at next (F:\cmdb_frontend\node_modules\tapable\lib\Tapable.js:252:11)
    at F:\cmdb_frontend\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:40:4
    at loggingCallbackWrapper (F:\cmdb_frontend\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
 @ ./src/main.js 29:0-33
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server @/main

ERROR in ./src/styles/iview-ui.less
Module build failed: ModuleBuildError: Module build failed: Can't resolve './iview/src/styles/index.less' in 'F:\cmdb_frontend\src\styles'
 @ F:\cmdb_frontend\src\styles\iview-ui.less (line 1, column 0)
 near lines:
   
   @import 'iview/src/styles/index.less';
   //@import (inline) 'iview/dist/styles/iview.css';
    at runLoaders (F:\cmdb_frontend\node_modules\webpack\lib\NormalModule.js:195:19)
    at F:\cmdb_frontend\node_modules\loader-runner\lib\LoaderRunner.js:364:11
    at F:\cmdb_frontend\node_modules\loader-runner\lib\LoaderRunner.js:230:18
    at context.callback (F:\cmdb_frontend\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at F:\cmdb_frontend\node_modules\less-loader\index.js:68:16
    at F:\cmdb_frontend\node_modules\less\lib\less\render.js:26:35
    at F:\cmdb_frontend\node_modules\less\lib\less\parse.js:62:33
    at ImportVisitor.finish [as _finish] (F:\cmdb_frontend\node_modules\less\lib\less\parser\parser.js:180:28)
    at ImportVisitor._onSequencerEmpty (F:\cmdb_frontend\node_modules\less\lib\less\visitors\import-visitor.js:35:14)
    at ImportSequencer.tryRun (F:\cmdb_frontend\node_modules\less\lib\less\visitors\import-sequencer.js:50:14)
    at F:\cmdb_frontend\node_modules\less\lib\less\visitors\import-sequencer.js:19:25
    at fileParsedFunc (F:\cmdb_frontend\node_modules\less\lib\less\import-manager.js:50:17)
    at F:\cmdb_frontend\node_modules\less\lib\less\import-manager.js:121:17
    at F:\cmdb_frontend\node_modules\less-loader\index.js:111:5
    at onError (F:\cmdb_frontend\node_modules\enhanced-resolve\lib\Resolver.js:65:10)
    at loggingCallbackWrapper (F:\cmdb_frontend\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at runAfter (F:\cmdb_frontend\node_modules\enhanced-resolve\lib\Resolver.js:158:4)
    at innerCallback (F:\cmdb_frontend\node_modules\enhanced-resolve\lib\Resolver.js:146:3)
    at loggingCallbackWrapper (F:\cmdb_frontend\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at next (F:\cmdb_frontend\node_modules\tapable\lib\Tapable.js:252:11)
    at F:\cmdb_frontend\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:40:4
    at loggingCallbackWrapper (F:\cmdb_frontend\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
 @ ./src/styles/iview-ui.less
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server @/main
Child html-webpack-plugin for "..\index.html":
                                   Asset      Size  Chunks             Chunk Names
    f6d337535f2f6b5e0536.hot-update.json  44 bytes          [emitted]  
     + 1 hidden asset
       4 modules
Child extract-text-webpack-plugin:
                                   Asset      Size  Chunks             Chunk Names
    ecd069bd6fd94090d225.hot-update.json  44 bytes          [emitted]  
       [0] ./node_modules/css-hot-loader!./node_modules/autoprefixer-loader!./node_modules/less-loader!./src/styles/iview-ui.less 307 bytes {1} [built] [failed] [1 error]
       [2] ./node_modules/style-loader/addStyles.js 6.91 kB {1} [built]
        + 1 hidden module
    
    ERROR in ./node_modules/css-hot-loader!./node_modules/autoprefixer-loader!./node_modules/less-loader!./src/styles/iview-ui.less
    Module build failed: Can't resolve './iview/src/styles/index.less' in 'F:\cmdb_frontend\src\styles'
     @ F:\cmdb_frontend\src\styles\iview-ui.less (line 1, column 0)
     near lines:
       
       @import 'iview/src/styles/index.less';
       //@import (inline) 'iview/dist/styles/iview.css';
     @ ./node_modules/style-loader!./node_modules/css-hot-loader!./node_modules/autoprefixer-loader!./node_modules/less-loader!./src/styles/iview-ui.less 4:14-173 13:2-17:4 14:20-179
Child extract-text-webpack-plugin:
                                   Asset      Size  Chunks             Chunk Names
    cc6194f98e9f49e5e9dc.hot-update.json  44 bytes          [emitted]  
       [2] ./node_modules/css-hot-loader!./node_modules/autoprefixer-loader!./node_modules/less-loader!./src/styles/iview-ui.less 307 bytes {0} [built] [failed] [1 error]
       [4] ./node_modules/style-loader/addStyles.js 6.91 kB {0} [built]
        + 1 hidden module
    
    ERROR in ./node_modules/css-hot-loader!./node_modules/autoprefixer-loader!./node_modules/less-loader!./src/styles/iview-ui.less
    Module build failed: Can't resolve './iview/src/styles/index.less' in 'F:\cmdb_frontend\src\styles'
     @ F:\cmdb_frontend\src\styles\iview-ui.less (line 1, column 0)
     near lines:
       
       @import 'iview/src/styles/index.less';
       //@import (inline) 'iview/dist/styles/iview.css';
     @ ./node_modules/style-loader!./node_modules/css-hot-loader!./node_modules/autoprefixer-loader!./node_modules/less-loader!./src/styles/iview-ui.less 4:14-173 13:2-17:4 14:20-179
webpack: Failed to compile.

**Comment by lison16** [comment]
现已修复
