### ISSUE TITLE
Happy[happybabel]: Version: 4.0.1. Threads: 4 (shared pool)

### ISSUE THREAD

**Issue by qhdhiman** [iview/iview-admin#561]
Happy[happybabel]: Version: 4.0.1. Threads: 4 (shared pool)
(node:2395) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND localhost
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iview-admin@1.3.1 dev: `webpack-dev-server --content-base ./ --open --inline --hot --compress --config build/webpack.dev.config.js`

**Comment by ZXiner** [comment]
同问

**Comment by fuxiangduan** [comment]
同问

**Comment by WithLin0510** [comment]
同问

**Comment by tkggusraqk** [comment]
同样有这个错

**Comment by Fengmaybe** [comment]
我的问题是：
Happy[happybabel]: Version: 4.0.0. Threads: 4 (shared pool)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8080

解决：
因为这个项目是iview admin 开发的 ,他好像只会用8080  
然后我再此之前打开另外一个项目 端口号8080
冲突了，关掉之前的8080 就可以可
好像用iview admin 当占用时不会另起一个
