### ISSUE TITLE
npm run build error

### ISSUE THREAD

**Issue by sowork** [iview/iview-admin#604]
$ npm run build

> iview-admin@1.3.1 build C:\Users\dn\Desktop\iview-admin-dev
> webpack --progress --hide-modules --config build/webpack.prod.config.js

clean-webpack-plugin: C:\Users\dn\Desktop\iview-admin-dev\dist\* has been removed.
Happy[happybabel]: Version: 4.0.1. Threads: 4 (shared pool)
(node:8844) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
internal/child_process.js:323
    throw errnoException(err, 'spawn');
    ^

Error: spawn EBUSY
    at _errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at exports.spawn (child_process.js:502:9)
    at exports.fork (child_process.js:103:10)
    at open (C:\Users\dn\Desktop\iview-admin-dev\node_modules\happypack\lib\HappyThread.js:45:12)
    at C:\Users\dn\Desktop\iview-admin-dev\node_modules\happypack\node_modules\async\lib\async.js:713:13
    at async.forEachOf.async.eachOf (C:\Users\dn\Desktop\iview-admin-dev\node_modules\happypack\node_modules\async\lib\async.js:233:13)
    at _parallel (C:\Users\dn\Desktop\iview-admin-dev\node_modules\happypack\node_modules\async\lib\async.js:712:9)
    at Object.async.parallel (C:\Users\dn\Desktop\iview-admin-dev\node_modules\happypack\node_modules\async\lib\async.js:726:9)
    at Object.start (C:\Users\dn\Desktop\iview-admin-dev\node_modules\happypack\lib\HappyThreadPool.js:60:13)
    at launchAndConfigureThreads (C:\Users\dn\Desktop\iview-admin-dev\node_modules\happypack\lib\HappyPlugin.js:172:23)
    at C:\Users\dn\Desktop\iview-admin-dev\node_modules\happypack\node_modules\async\lib\async.js:713:13
    at iterate (C:\Users\dn\Desktop\iview-admin-dev\node_modules\happypack\node_modules\async\lib\async.js:262:13)
    at C:\Users\dn\Desktop\iview-admin-dev\node_modules\happypack\node_modules\async\lib\async.js:274:29
    at C:\Users\dn\Desktop\iview-admin-dev\node_modules\happypack\node_modules\async\lib\async.js:44:16
    at C:\Users\dn\Desktop\iview-admin-dev\node_modules\happypack\node_modules\async\lib\async.js:718:17
    at C:\Users\dn\Desktop\iview-admin-dev\node_modules\happypack\node_modules\async\lib\async.js:167:37
    at C:\Users\dn\Desktop\iview-admin-dev\node_modules\happypack\lib\HappyPlugin.js:154:9
    at C:\Users\dn\Desktop\iview-admin-dev\node_modules\happypack\node_modules\async\lib\async.js:721:13
    at C:\Users\dn\Desktop\iview-admin-dev\node_modules\happypack\node_modules\async\lib\async.js:52:16
    at done (C:\Users\dn\Desktop\iview-admin-dev\node_modules\happypack\node_modules\async\lib\async.js:246:17)
    at C:\Users\dn\Desktop\iview-admin-dev\node_modules\happypack\node_modules\async\lib\async.js:44:16
    at C:\Users\dn\Desktop\iview-admin-dev\node_modules\happypack\node_modules\async\lib\async.js:718:17
    at C:\Users\dn\Desktop\iview-admin-dev\node_modules\happypack\node_modules\async\lib\async.js:167:37
    at C:\Users\dn\Desktop\iview-admin-dev\node_modules\happypack\lib\WebpackUtils.js:185:16
    at onResolve (C:\Users\dn\Desktop\iview-admin-dev\node_modules\enhanced-resolve\lib\Resolver.js:70:11)
    at innerCallback (C:\Users\dn\Desktop\iview-admin-dev\node_modules\enhanced-resolve\lib\Resolver.js:143:22)
    at callbackWrapper (C:\Users\dn\Desktop\iview-admin-dev\node_modules\enhanced-resolve\lib\createInnerCallback.js:10:21)
    at next (C:\Users\dn\Desktop\iview-admin-dev\node_modules\tapable\lib\Tapable.js:249:35)
    at C:\Users\dn\Desktop\iview-admin-dev\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:39:22
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iview-admin@1.3.1 build: `webpack --progress --hide-modules --config build/webpack.prod.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iview-admin@1.3.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dn\AppData\Roaming\npm-cache\_logs\2018-04-27T11_52_11_448Z-debug.log

**Comment by ATM001** [comment]
same problem! how resolve it

**Comment by sowork** [comment]
@ATM001 The problem is that a resource is occupied, and if you can find out which resource is occupied, kill it, find it, how many times it will succeed

**Comment by hqzh** [comment]
try change node version
