### ISSUE TITLE
npm run dev: Callback must be a function

### ISSUE THREAD

**Issue by callmez** [iview/iview-admin#615]
错误信息如下
```js
Happy[happybabel]: Version: 4.0.1. Threads: 8 (shared pool)
fs.js:124
  throw new ERR_INVALID_CALLBACK();
  ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:124:9)
    at Object.fs.write (fs.js:642:14)
    at /Users/www/admin/build/webpack.dev.config.js:12:8
    at FSReqWrap.oncomplete (fs.js:136:20)

```

**Comment by Li-Xin-xyz** [comment]
如下：

1. [root@slave1 web-user-center-master]# npm run dev
2. 
3. > iview-admin@1.3.1 dev /opt/SoftWare/UserCenter/web-user-center-master
4. > webpack-dev-server --content-base ./ --open --inline --hot --compress --config build/webpack.dev.config.js
5. 
6. Happy[happybabel]: Version: 4.0.0. Threads: 1 (shared pool)
7. fs.js:124
8. throw new ERR_INVALID_CALLBACK();
9. ^
10. 
11. TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
12. at maybeCallback (fs.js:124:9)
13. at Object.fs.write (fs.js:642:14)
14. at /opt/SoftWare/UserCenter/web-user-center-master/build/webpack.dev.config.js:12:8
15. at FSReqWrap.oncomplete (fs.js:136:20)
16. npm ERR! code ELIFECYCLE
17. npm ERR! errno 1
18. npm ERR! iview-admin@1.3.1 dev: `webpack-dev-server --content-base ./ --open --inline --hot --compress --config build/webpack.dev.config.js`
19. npm ERR! Exit status 1
20. npm ERR! 
21. npm ERR! Failed at the iview-admin@1.3.1 dev script.
22. npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
23. 
24. npm ERR! A complete log of this run can be found in:
25. npm ERR!     /root/.npm/_logs/2018-05-07T13_49_06_285Z-debug.log

**Comment by Lstoryc** [comment]
我也一样～～ 求解

`npm run dev

> titans-admin@1.0.0 dev /Users/lstoryc/Desktop/devSpace/devSpace.Titans/titans-admin
> webpack-dev-server --host 0.0.0.0 --content-base ./ --open --inline --hot --compress --config build/webpack.dev.config.js

Happy[happybabel]: Version: 4.0.1. Threads: 4 (shared pool)
Project is running at http://0.0.0.0:8080/
webpack output is served from /dist/
Content not from webpack is served from /Users/lstoryc/Desktop/devSpace/devSpace.Titans/titans-admin
fs.js:124
  throw new ERR_INVALID_CALLBACK();
  ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:124:9)
    at Object.fs.write (fs.js:642:14)
    at /Users/lstoryc/Desktop/devSpace/devSpace.Titans/titans-admin/build/webpack.dev.config.js:12:6
    at FSReqWrap.oncomplete (fs.js:136:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! titans-admin@1.0.0 dev: `webpack-dev-server --host 0.0.0.0 --content-base ./ --open --inline --hot --compress --config build/webpack.dev.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the titans-admin@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lstoryc/.npm/_logs/2018-05-08T13_29_40_321Z-debug.log`

**Comment by Lstoryc** [comment]
已解决～～ 

应该就是node版本问题，fs估计接口改了，不兼容现在这个代码

我现在用这个版本node没问题 

`Lstoryc-MBP:titans-admin lstoryc$ node -v
v8.11.1`

**Comment by itshizhan** [comment]
node 版本问题，node v10 以上 fs.write 的callback 是必须的。
如果不想重新安装node到低版本
将webpack.dev.config.js 和 webpack.prod.config.js 中的代码修改即可：
```js
// 具体里面的参数参考node v10 的文档，或者直接删除可选的参数
fs.write(fd, buf, function(err, written, buffer) {});
```
这个就是写入一个环境变量

**Comment by WildDylan** [comment]
@itshizhan That's worked

**Comment by AmeerTaweel** [comment]
@itshizhan it worked for me too, thanks.

**Comment by hqzh** [comment]
各个项目node版本不一致建议下载一个node切换器[nvm](https://github.com/coreybutler/nvm-windows)  ,这样不用考虑会破坏脚手架,而且切换也柔顺丝滑

**Comment by Donlei** [comment]
Node version problem, node v10 above fs. Write callback is a must.
If you don't want to reinstall node to a lower version
Modify the code in webpack.dev.config.js and webpack.prod.config.js to:
// refer to the node v10 documentation for the specific parameters, or delete the optional parameters directly
Write (fd, buf, function(err, written, buffer) {});

**Comment by duzhenlin** [comment]
@itshizhan That's worked, thanks.

**Comment by originalstacie** [comment]
> node 版本问题，node v10 以上 fs.write 的callback 是必须的。
> 如果不想重新安装node到低版本
> 将webpack.dev.config.js 和 webpack.prod.config.js 中的代码修改即可：
> 
> ```js
> // 具体里面的参数参考node v10 的文档，或者直接删除可选的参数
> fs.write(fd, buf, function(err, written, buffer) {});
> ```
> 
> 这个就是写入一个

**Comment by originalstacie** [comment]
it works! thanks so much!
